import streamlit as st
import requests
import io
from PIL import Image
import json

# --- PAGE CONFIG ---
st.set_page_config(page_title="AI Image Generator", page_icon="🎨", layout="wide")

st.title("🎨 AI Synthetic Data Generator")
st.markdown("**Week 11, Day 1: Text-to-Image Pipeline**")

# --- SIDEBAR: API SETUP ---
st.sidebar.header("⚙️ Configuration")
api_key = st.sidebar.text_input("Hugging Face API Token", type="password", help="Get free token from huggingface.co/settings/tokens")

# --- CONSTANTS ---
# Updated API URL as per the error message recommendation
API_URL = "https://router.huggingface.co/hf-inference/models/stabilityai/stable-diffusion-xl-base-1.0"

# --- CORE LOGIC ---
def query_model(payload, headers):
    """
    Sends request to Hugging Face. 
    Includes error handling to catch non-image responses.
    """
    response = requests.post(API_URL, headers=headers, json=payload)
    
    # Check if the request was successful
    if response.status_code != 200:
        # If not 200, it's an error (likely JSON text)
        raise Exception(f"API Error {response.status_code}: {response.text}")
        
    return response.content

# --- MAIN APP ---
col1, col2 = st.columns([1, 2])

with col1:
    st.subheader("Prompt Engineering")
    prompt = st.text_area("Describe the image:", height=150, placeholder="A futuristic construction worker wearing a neon safety vest, cyberpunk city background, 8k resolution, photorealistic")
    
    generate_btn = st.button("Generate Image", type="primary", use_container_width=True)

with col2:
    st.subheader("Result")
    
    if generate_btn:
        if not api_key:
            st.error("❌ Please enter your Hugging Face API Token in the sidebar.")
        elif not prompt:
            st.warning("Please enter a prompt.")
        else:
            headers = {"Authorization": f"Bearer {api_key}"}
            
            with st.spinner("Dreaming... (This takes 5-10 seconds)"):
                try:
                    # 1. Send Request
                    image_bytes = query_model({"inputs": prompt}, headers)
                    
                    # 2. Decode Image
                    image = Image.open(io.BytesIO(image_bytes))
                    
                    # 3. Display
                    st.image(image, caption="Generated by SDXL", use_container_width=True)
                    
                    # 4. Download Button
                    buf = io.BytesIO()
                    image.save(buf, format="PNG")
                    st.download_button(
                        label="💾 Download Synthetic Data",
                        data=buf.getvalue(),
                        file_name="synthetic_image.png",
                        mime="image/png"
                    )
                    
                except Exception as e:
                    # This will now print the ACTUAL error from Hugging Face
                    st.error("Generation Failed.")
                    st.warning(f"Details: {e}")
                    
                    if "503" in str(e):
                        st.info("💡 Hint: Error 503 usually means the model is 'Cold' and loading on the server. Wait 30 seconds and click Generate again.")
                    elif "401" in str(e):
                        st.info("💡 Hint: Error 401 means your API Token is invalid.")
                    elif "410" in str(e):
                         st.info("💡 Hint: Error 410 usually means the API endpoint URL has changed.")